Issue #2982332 by Insasse: New Riddle API
BurdaMagazinOrg/module-riddle_marketplace pull request #15
Opened 2018-07-13 11:58 UTC by ol0lll

2018-07-16 07:28 UTC, DiDebru commented on riddle_marketplace.post_update.php
> +  $module_settings = Drupal::configFactory()->get('riddle_marketplace.settings');
We need Drupal::configFactory()->getEditable(); here

2018-07-16 07:44 UTC, Insasse commented on riddle_marketplace.post_update.php
> +  }
And we need to save the settings here
$module_settings->save();

2018-07-16 07:44 UTC, Insasse commented on riddle_marketplace.post_update.php
> +  }
between line 17 and 18.

2018-07-16 07:52 UTC, Insasse commented
Now its working fine for me thanks for the patch. I've also added a tip in the comment section to export the config after this update.

2018-07-16 11:54 UTC, dbosen requested changes

2018-07-16 11:54 UTC, dbosen commented on modules/media_riddle_marketplace/src/Plugin/MediaEntity/Type/Riddle.php
> +              $response = \Drupal::httpClient()->head($riddle['image']);
Please inject this

2018-07-16 11:54 UTC, dbosen commented on modules/media_riddle_marketplace/src/Plugin/MediaEntity/Type/Riddle.php
> +              $format = ExtensionGuesser::getInstance()
You can use a drupal core service for that, either file.mime_type.guesser.extension or file.mime_type.guesser

2018-07-17 07:03 UTC, Insasse commented on modules/media_riddle_marketplace/src/Plugin/MediaEntity/Type/Riddle.php
> +   *   The guessed extension or null if it cannot be guessed
Hope this is not too pedantic but every comment should end with a full stop.

2018-07-18 09:52 UTC, dbosen approved these changes

2018-07-18 09:53 UTC, merged